name: sync-github-repo-settings

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  sync-github-repo-settings:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Update Repository Settings
        uses: joshjohanning/bulk-github-repo-settings-sync-action@v1.3.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          repositories-file: 'repos.yml'
          allow-squash-merge: true
          allow-merge-commit: false
          allow-rebase-merge: false
          allow-auto-merge: true
          delete-branch-on-merge: true
          allow-update-branch: true
          enable-default-code-scanning: true
          dependabot-pr-title: 'chore: update dependabot.yml'
          dry-run: ${{ github.event_name == 'pull_request' }} # dry run if PR
